# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: 'Kani Rust Verifier'
description: 'Run the Kani Rust Verifier on a Rust Crate'
author: 'Kani Contributors'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  command:
    description: 'Command to run.'
    required: false
    default: 'cargo-kani'
  working-directory:
    description: 'Directory to run kani on.'
    required: false
    default: '.'
  args:
    description: 'Arguments to pass to kani.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.7
      with:
        # From https://github.com/model-checking/kani/blob/kani-0.15.0/rust-toolchain.toml
        # Should be updated every time we update the version to keep in sync.
        # This should be automated https://github.com/model-checking/kani-github-action/issues/9
        toolchain: nightly-2022-11-06
        override: true

    - name: Install Kani
      shell: bash
      run: |
        export KANI_VERSION="0.15.0";
        cargo install --version $KANI_VERSION --locked kani-verifier;
        cargo-kani setup;

    - name: Run Kani
      shell: bash
      run: |
        cd ${{ inputs.working-directory }};
        ${{ inputs.command }} ${{ inputs.args }}

