# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: 'Kani Rust Verifier'
description: 'Run the Kani Rust Verifier on a Rust Crate'
author: 'Kani Contributors'

branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  command:
    description: 'Command to run.'
    required: false
    default: 'cargo-kani'
  working-directory:
    description: 'Directory to run kani on.'
    required: false
    default: '.'
  args:
    description: 'Arguments to pass to kani.'
    required: false
    default: ''
  enable-propproof:
    description: 'Experimental: Allow Kani to verify proptest harnesses using the PropProof feature'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.7
      with:
        # From https://github.com/model-checking/kani/blob/kani-0.21.0/rust-toolchain.toml
        # Should be updated every time we update the version to keep in sync.
        # This should be automated https://github.com/model-checking/kani-github-action/issues/9
        toolchain: nightly-2022-12-11
        override: true

    - name: Install Kani
      shell: bash
      run: |
        export KANI_VERSION="0.21.0";
        cargo install --version $KANI_VERSION --locked kani-verifier;
        cargo-kani setup;

    - name: Install PropProof
      if: ${{ inputs.enable-propproof }}
      uses: actions/checkout@v3
      with:
        repository: model-checking/kani
        ref: features/proptest
        path: propproof
        submodules: true
      shell: bash
      run: |
        echo "paths = [\"${{ GITHUB_WORKSPACE }}/propproof\"]" > $HOME/.cargo/config.toml

    - name: Run Kani
      shell: bash
      run: |
        cd ${{ inputs.working-directory }};
        ${{ inputs.command }} ${{ inputs.args }}
